name: TeleportWaypoints
version: 2.0
author: klin
main: com.klin.teleportwaypoints.TeleportWaypoints
api-version: 1.14
commands:
  worldhome:
    description: sets current world to be compatible with /sethome
  worldcamp:
    description: sets current world to be compatible with /setcamp
  packup:
    description: clears all camps
  setspawn:
    description: sets spawn for current world to present location
  fake:
    description: progresses specified waypoint to 1 before completion
    usage: /<command> <index>
  givepoint:
    description: gives user 1 waypoint point
  readwaypoints:
    description: reads config files into game
  clearwaitlist:
    description: clears waitlist to use teleport
  setpointsrequired:
    description: sets required points to complete a waypoint
  sethome:
    description: sets a player specific home
  home:
    description: teleports user to their home
  setcamp:
    description: sets a player specific camp
  camp:
    description: teleports user to their camp
  waypoint:
    description: opens users collection of visited waypoints
    aliases: wa
  spawn:
    description: teleports user to the spawn of the respective world
